name: "10.02.lab01 deploy"

on:
  push:
    branches: [main]
    paths: ["ch10/01/lab01/infra/*.tf", "ch10/01/lab01/infra/*.tfvars"]

permissions:
  contents: read
  id-token: write

concurrency:
  group: gallery-k0-10.02.lab01-deploy
  cancel-in-progress: false

env:
  TF_VERSION: "1.14.7"
  AWS_REGION: "ap-northeast-2"
  WORKING_DIR: "ch10/01/lab01/infra"

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_IAMROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # [수정] 외부 백엔드 설정 파일(hcl) 주입
      - name: Terraform Init
        run: terraform init -input=false -backend-config="env.dev.backend.hcl"

      # [수정] 배포 시 변수 파일(tfvars) 주입
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var-file="env.dev.tfvars"
    # 변수가 없는 인프라라 input 없어도 괜찮음