name: 10.02.lab01 review

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths: ["ch10/01/lab01/infra/*.tf"]

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  TF_VERSION: "1.14.7"
  AWS_REGION: "ap-northeast-2"
  WORKING_DIR: "ch10/01/lab01/infra"

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_IAMROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
 
      - name: Terraform Init
        run: terraform init # -backend=false 이건 백엔드안할때
        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false

      - name: Fail if Plan Failed
        if: steps.plan.outcome == 'failure'
        run: exit 1